version: '3'

services:
  web:
    build:
      context: ./app
    ports:
      - "3000:3000"
    depends_on:
      - dynamodb
    links:
      - dynamodb

  dynamodb:
    build:
      context: ./dynamodb
    ports:
      - "8000:8000"
